# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Todor V. Ivanov
title: Big Data Expert and Researcher
email: todor.v.ivanov@gmail.com
website: https://t-ivanov.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: t-ivanov
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: tivanov
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
#googleplus_username: https://scholar.google.com/citations?user=cPnoKVEAAAAJ&hl=en
googlescholar_username: cPnoKVEAAAAJ&hl
orcid_username: 0000-0002-9679-8947

# Additional icon links
additional_links:
#  - title: google_scholar
#    icon: fas fa-globe
#    url: https://scholar.google.com/citations?user=cPnoKVEAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Ivanov.png
about_content: | # this will include new lines to allow paragraphs
  I am interested in the design and benchmarking of complex distributed software systems or data-intensive applications. In particular, I am interested in software architectures, virtualization, performance optimizations, scalability, effective storage and processing of structured and unstructured data in large systems.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Goethe University Frankfurt
        caption: 2014 - 2019
        sub_title: Doctorate of Natural Sciences (Dr. rer. nat.) in Computer Science
        quote: >
          Databases and Information Systems (DBIS), Goethe University Frankfurt
        description: | # this will include new lines to allow paragraphs
          [Doctoral thesis: “Classifying, Evaluating and Advancing Big Data Benchmarks”](http://publikationen.ub.uni-frankfurt.de/frontdoor/index/index/docId/51157)
          
          Thesis advisor: Prof. Dott. -Ing. Roberto V. Zicari

      - layout: left
        title: Technical University of Darmstadt
        caption: 2011 - 2014
        sub_title: Master of Science in Distributed Software Systems
        quote: >
          Department of Computer Science, Technical University of Darmstadt
        description: | # this will include new lines to allow paragraphs
          Master thesis: Benchmarking Hadoop Clusters: An Empirical Study
          
          Thesis advisors: Alejandro Buchmann (TU Darmstadt) and Roberto V. Zicari (Goethe University Frankfurt)

      - layout: left
        title: Technical University of Darmstadt
        caption: 2003 - 2009
        sub_title: Bachelor of Science in Computational Engineering
        quote: >
          Department of Computational Engineering, Technical University of Darmstadt
        description: | # this will include new lines to allow paragraphs
          Bachelor thesis: Analysis of Database Performance in Virtual Environments
          
          Thesis advisors: Alejandro Buchmann (TU Darmstadt) and Ilia Petrov (TU Darmstadt)


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Big Data and AI Pipeline Framework: Technology Analysis from a Benchmarking Perspective
      
        Arne Berre, Aphrodite Tsalgatidou, Chiara Francalanci, **Todor Ivanov**, Tomas Pariente-Lobo,
        Ricardo Ruiz-Saiz, Inna Novalija and Marko Grobelnik,
      
        *In Technologies and Applications for Big Data Value, Springer, Cham , pp. 63–88, 2022*


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
